name: CI/CD Pipeline
on:
  push:
    branches: [ main ]

jobs:
  continuous-integration:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.10
      - name: Build the docker-compose stack
        run: ./run.sh up -d 
      - name: Check running containers
        run: docker ps -a
      - name: Run unit Test
        run: ./run.sh dj test